#!/bin/sh
mkdir pdfs
cd pdfs
mkdir 210
cd 210

curl -LO https://developer.salesforce.com/resource/pdfs/Lightning_Components_Cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_winter04_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_spring04_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_summer04_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_winter05_release_notes.pdf
#skipped https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_spring05_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_summer05_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_winter06_release_notes.pdf
#skipped https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_spring06_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_summer06_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/146/latest/en-us/sfdc/pdf/salesforce_winter07_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/146/latest/en-us/sfdc/pdf/salesforce_spring07_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/148/latest/en-us/sfdc/pdf/salesforce_summer07_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/150/latest/en-us/sfdc/pdf/salesforce_winter08_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/152/latest/en-us/sfdc/pdf/salesforce_spring08_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/154/latest/en-us/sfdc/pdf/salesforce_summer08_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/156/latest/en-us/sfdc/pdf/salesforce_winter09_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/158/latest/en-us/sfdc/pdf/salesforce_spring09_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/160/latest/en-us/sfdc/pdf/salesforce_summer09_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/162/latest/en-us/sfdc/pdf/salesforce_winter10_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/164/latest/en-us/sfdc/pdf/salesforce_spring10_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/166/latest/en-us/sfdc/pdf/salesforce_summer10_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/168/latest/en-us/sfdc/pdf/salesforce_winter11_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/170/latest/en-us/sfdc/pdf/salesforce_spring11_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/172/latest/en-us/sfdc/pdf/salesforce_summer11_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/174/latest/en-us/sfdc/pdf/salesforce_winter12_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/176/latest/en-us/sfdc/pdf/salesforce_spring12_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/178/latest/en-us/sfdc/pdf/salesforce_summer12_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/180/latest/en-us/sfdc/pdf/salesforce_winter13_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/182/latest/en-us/sfdc/pdf/salesforce_spring13_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/salesforce_summer13_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/186/latest/en-us/sfdc/pdf/salesforce_winter14_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/188/latest/en-us/sfdc/pdf/salesforce_spring14_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/190/latest/en-us/sfdc/pdf/salesforce_summer14_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/192/latest/en-us/sfdc/pdf/bi_dev_guide_eql.pdf
curl -LO https://resources.docs.salesforce.com/192/latest/en-us/sfdc/pdf/salesforce_winter15_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_spring18_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/record_locking_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_appexchange_install_guide.pdf
curl -LO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_jigsaw_clean_user_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_query_search_optimization_developer_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_spring15_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/service_communities_guide.pdf
curl -LO https://resources.docs.salesforce.com/196/latest/en-us/sfdc/pdf/salesforce_summer15_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/196/latest/en-us/sfdc/pdf/salesforce_supported_browsers_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/198/0/en-us/sfdc/pdf/salesforce_knowledge_import_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/198/0/en-us/sfdc/pdf/salesforce_knowledge_setup_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/isv_pkg.pdf
curl -LO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/lex_considerations.pdf
curl -LO https://resources.docs.salesforce.com/196/latest/en-us/sfdc/pdf/salesforce1_api_guide.pdf
curl -LO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/salesforce_pagelayouts_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/salesforce_winter16_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_approvals_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_email_approval_faq.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_exchange_sync_user.pdf
curl -LO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_filtered_lookups_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_spring16_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_web_integration_links.pdf
curl -LO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_workflow_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/202/latest/en-us/sfdc/pdf/salesforce_importpersonal_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/202/latest/en-us/sfdc/pdf/salesforce_recordtypes_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/202/latest/en-us/sfdc/pdf/salesforce_summer16_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/202/latest/en-us/sfdc/pdf/salesforce_workbench_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/204/latest/en-us/sfdc/pdf/salesforce_communities_implementation.pdf
curl -LO https://resources.docs.salesforce.com/204/latest/en-us/sfdc/pdf/salesforce_winter17_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/206/latest/en-us/sfdc/pdf/salesforce_spring17_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/salesforce_summer17_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/210/latest/en-us/sfdc/pdf/salesforce_winter18_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaAnalytics.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaChannelAdminGuide.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaConversationBuddy.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaDataAdapter.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaDataAdaptorDeveloperGuide.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaFacebookGlobalPages.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaGettingStarted.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaImplementationGuide.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaProfileBuddy.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaReachBuddy.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaYouTubeBrandChannels.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaYouTubeOneChannelFAQ.pdf
curl -LO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/MarketingCloudBuddyMediaImplementationGuide.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/CheckoutUserGuide.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/ext-svc-overview.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/field_service_lightning_guide.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/identity_connect_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Apex_Code_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_CRM_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_CRM_Lightning_Experience_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Custom_Metadata_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Formulas_Developer_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Git_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_LightningComponents_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Process_Automation_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Query_Search_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Record-Locking-Cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Reports_and_Dashboards_Rest_API_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Rest_API_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_S1-Admin_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_S1-Developer_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Security_Admin_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Security_Developer_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Service_Cloud_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Soap_API_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Visualforce_Developer_cheatsheet_web.pdf
curl -LO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/InsightsPartnerOverviews.pdf
curl -LO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/MC_ReleaseNotes_August13.pdf
curl -LO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/MCNov13ReleaseNotes.pdf
curl -LO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/MCReleaseNotesSpring14.pdf
curl -LO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/StreamActivityFAQ.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/MarketingCloudRadian6Introduction.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6AnalysisDashboard.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6EngagementConsole.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6EngagementConsoleSpecifications.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6FacebookManagedAccounts.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6Insights.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6Mobile.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6Reports.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6SummaryDashboard.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6SuperUsers.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6TopicProfile.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6TopicProfileOptimization.pdf
curl -LO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6TwitterManagedAccounts.pdf
curl -LO https://resources.docs.salesforce.com/servicesdk/0/4/en-us/pdf/service_sdk_android.pdf
curl -LO https://resources.docs.salesforce.com/servicesdk/2/0/en-us/pdf/service_sdk_ios.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/actions_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/analytics.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/apex_ajax.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/apex_api.pdf
curl -LO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/apex_workbook.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/api_action.pdf
curl -LO https://resources.docs.salesforce.com/172/latest/en-us/sfdc/pdf/api_apex_rest.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/api_asynch.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/api_console.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/api_cti.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/api_meta.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/api_rest.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/api_rest_industries.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/api_social.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/api_streaming.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/api_tooling.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/api_ui.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/appexchange_install_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/appexchange_publishing_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/apps.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/async_soql_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/basics.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/bi_admin_guide_data_integration_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/bi_admin_guide_security.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/bi_admin_guide_setup.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_bindings.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_ext_data.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_ext_data_format.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_json.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_rest.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_saql.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_sdk.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_wave_templates.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_xmd.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/big_objects_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/canvas_framework.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/case_feed_dev_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/chatter.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/collaboration.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/collaboration_admin.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/communities.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/communities_dev.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/community_templates.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/console.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/custom_metadata_types_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/data_dot_com_clean_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/204/latest/en-us/sfdc/pdf/data_pipelines.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/datacom_salesforce_record_matching.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/datadotcom_api_dev_guide.pdf
curl -LO https://resources.docs.salesforce.com/178/latest/en-us/sfdc/pdf/dbcom_apex_language_reference.pdf
curl -LO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/dbcom_api_asynch.pdf
curl -LO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/dbcom_api_meta.pdf
curl -LO https://resources.docs.salesforce.com/174/latest/en-us/sfdc/pdf/dbcom_api_rest.pdf
curl -LO https://resources.docs.salesforce.com/176/latest/en-us/sfdc/pdf/dbcom_api_streaming.pdf
curl -LO https://resources.docs.salesforce.com/178/latest/en-us/sfdc/pdf/dbcom_chatter_rest_api.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/deploy_sandboxes.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/draes.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/eclipse.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/einstein_platform_services.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/extend_click.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/extend_code.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/federated_search.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/field_history_retention.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/financial_services.pdf
curl -LO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/forcecom_workbook.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/forecasts.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/formula_date_time_tipsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/fsc_dev_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/generate_orders_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/healthcare.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/health_cloud_dev_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/integration_patterns_and_practices.pdf
curl -LO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/integration_workbook.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/jsapi_chatteranswers.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/lex.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/lightning.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/lightning_experience_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/lightning_knowledge_guide.pdf
curl -LO https://resources.docs.salesforce.com/210/latest/en-us/sfdc/pdf/limits_limitations.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/live_agent_administrator.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/live_agent_dev_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/live_agent_rest.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/live_agent_support_agents.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/live_agent_support_supervisors.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/mobile_sdk.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/object_reference.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/oem_user_license_comparison_tipsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/omnichannel_supervisor.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/organization_sync.pdf
curl -LO https://resources.docs.salesforce.com/136/latest/en-us/sfdc/pdf/ot.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/pardot_get_start.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/platform_events.pdf
curl -LO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/sales_admins.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/sales_einstein_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/sales_users.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_admin_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_guide.pdf
curl -LO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce1_guide_admin.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_mobile_security.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_url_schemes.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_user_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_agent_console_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_analytics_folder_sharing_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_analytics_overview_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_analytics_rest_api.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_answers_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_apex_language_reference.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_app_limits_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_assets_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_axm_blackberry_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_axm_user_guide_for_blackberry.pdf
curl -LO https://resources.docs.salesforce.com/146/latest/en-us/sfdc/pdf/salesforce_axm_6.0_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_B2C_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_busprocess_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_campaign_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_campaigns_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_case_feed_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_case_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_case_interaction_setup_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_chatter_rest_api.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_chatterplus_tipsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_client_autoupdate_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_communities_managers_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_community_identity_templates.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_conflict_res_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_console_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_content_delivery_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_content_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_convertleads_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_creating_on_demand_apps.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_cti_admin_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_cti_demo_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_cti_developer_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_cti_developer_guide_2.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_cti_enduser_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_customer_portal_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_dashboard_filters_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_dashboard_samples.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_dashboards_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_data_import_wizard_tipsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_data_loader.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_data_quality_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_data_quality_duplicate_prevention.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_defer_sharing_tipsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_developer_environment_dotnet_tipsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_developer_environment_tipsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_development_lifecycle.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_divisions_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_dynamic_dashboards_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_ee_upgrade_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_entitlements_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_exchange_sync_admin_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_external_identity_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_field_names_reference.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_field_service_lightning_managed_package.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_file_sync_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_files_connect_implementation.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_admin_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_install_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_quick_start.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_upgrade_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_flash_builder.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_flash_builder_quickstart.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_forecastFAQ_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_forecastsetup_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_forecastuser_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_formula_size_tipsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_formulas_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_groupcal_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_health_cloud_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_HTMLtemplates_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_ideas_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_ideas_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_ideas_theme_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_identity_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_implementing_territory_mgmt2_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_import_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_jigsaw_clean_admin_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_jigsaw_config.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_jigsaw_jfs_uninstall.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_knowledge_dev_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_knowledge_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_large_data_volumes_bp.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_lead_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_leads_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_limits_practices.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_lma_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_mailmerge.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_mailmerge_upload_guidelines.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_massdelete_undoimport.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_migration_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_mobile_implementation.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_mobile_push_notifications_implementation.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_mobile_user_guide_android.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_mobile_user_guide_for_iphone.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_office_edition_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_office_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_offline_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_offline_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_opportunity_trending_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_orders_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_packaging_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_pages_developers_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_partner_portal_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_placeorder_rest_api.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_platform_encryption_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_platform_encryption_tipsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_platform_glossary.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_platform_mobile_services.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_platform_portal_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_portal_to_community_migration_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_products_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_profile_tabs_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_profile_tabs_styleguide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_pubs_style_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_questions_portal_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_record_access_under_the_hood.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_relgroups_getstart.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_report_builder_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_report_cross_filters_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_report_joined_format_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_report_summary_functions_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_reportperformance_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_reports_bucketing_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_reports_enhanced_reports_tab_tipsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_reports_schedule_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_salesrep_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_security_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_selfservice_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_selfservice_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_sfo_release_notes.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_sharing_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_sharing_users_tipsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_single_sign_on.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_solutions_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_solutions_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_soql_sosl.pdf
curl -LO https://resources.docs.salesforce.com/192/latest/en-us/sfdc/pdf/salesforce_studio_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_supportadmin_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_supportrep_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_TEadmin_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_technical_requirements.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_territories_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_territories_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_TEuser_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_useful_approval_processes.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_useful_formula_fields.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_useful_validation_formulas.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_useful_workflow_rules.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_using_multiple_currencies.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_views_cheatsheet.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_visualforce_best_practices.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_voice_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_vpm_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_wm_peripherals_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/secure_coding.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/security_certificate_changes.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/service_dev.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/service_presence_administrators.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/service_presence_developer_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/setup.pdf
curl -LO https://resources.docs.salesforce.com/210/latest/en-us/sfdc/pdf/sf.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/sfdx_cli_reference.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/sfdx_dev.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/sfdx_ide2.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/sfdx_setup.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/sfo_getting_started_guide.pdf
curl -LO https://resources.docs.salesforce.com/138/latest/en-us/sfdc/pdf/sforce_API.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/sharing_architecture.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/smb_sales_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/smb_sales_impl_guide_2.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/snapins.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/snapins_web_dev_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/social_customer_service_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/sos_administrators.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/state_country_picklists_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/support.pdf
curl -LO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/support_admins.pdf
curl -LO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/support_agents.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/team_selling_implementation_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/tm_decision_guide.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/utility_bar_impl_guide.pdf
curl -LO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/wb_siteforce.pdf
curl -LO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/workbook_analytics.pdf
curl -LO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/workbook_database.pdf
curl -LO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/workbook_flow.pdf
curl -LO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/workbook_security.pdf
curl -LO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/workbook_service_cloud.pdf
curl -LO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/workbook_vf.pdf
curl -LO https://resources.docs.salesforce.com/sfdc/pdf/workcom_implementation_guide.pdf
