#!/bin/sh
mkdir -p pdfs
cd pdfs
mkdir -p 224
cd 224

# release notes
echo "1/447 salesforce_winter04_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_winter04_release_notes.pdf
echo "2/447 salesforce_spring04_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_spring04_release_notes.pdf
echo "3/447 salesforce_summer04_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_summer04_release_notes.pdf
echo "4/447 salesforce_winter05_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_winter05_release_notes.pdf
#skipped https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_spring05_release_notes.pdf
echo "5/447 salesforce_summer05_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_summer05_release_notes.pdf
echo "6/447 salesforce_winter06_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_winter06_release_notes.pdf
#skipped https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_spring06_release_notes.pdf
echo "7/447 salesforce_summer06_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_summer06_release_notes.pdf
echo "8/447 salesforce_winter07_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/144/latest/en-us/sfdc/pdf/salesforce_winter07_release_notes.pdf
echo "9/447 salesforce_spring07_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/144/latest/en-us/sfdc/pdf/salesforce_spring07_release_notes.pdf
echo "10/447 salesforce_summer07_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/146/latest/en-us/sfdc/pdf/salesforce_summer07_release_notes.pdf
echo "11/447 salesforce_winter08_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/148/latest/en-us/sfdc/pdf/salesforce_winter08_release_notes.pdf
echo "12/447 salesforce_spring08_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/150/latest/en-us/sfdc/pdf/salesforce_spring08_release_notes.pdf
echo "13/447 salesforce_summer08_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/152/latest/en-us/sfdc/pdf/salesforce_summer08_release_notes.pdf
echo "14/447 salesforce_winter09_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/154/latest/en-us/sfdc/pdf/salesforce_winter09_release_notes.pdf
echo "15/447 salesforce_spring09_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/156/latest/en-us/sfdc/pdf/salesforce_spring09_release_notes.pdf
echo "16/447 salesforce_summer09_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/158/latest/en-us/sfdc/pdf/salesforce_summer09_release_notes.pdf
echo "17/447 salesforce_winter10_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/160/latest/en-us/sfdc/pdf/salesforce_winter10_release_notes.pdf
echo "18/447 salesforce_spring10_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/162/latest/en-us/sfdc/pdf/salesforce_spring10_release_notes.pdf
echo "19/447 salesforce_summer10_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/164/latest/en-us/sfdc/pdf/salesforce_summer10_release_notes.pdf
echo "20/447 salesforce_winter11_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/166/latest/en-us/sfdc/pdf/salesforce_winter11_release_notes.pdf
echo "21/447 salesforce_spring11_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/168/latest/en-us/sfdc/pdf/salesforce_spring11_release_notes.pdf
echo "22/447 salesforce_summer11_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/170/latest/en-us/sfdc/pdf/salesforce_summer11_release_notes.pdf
echo "23/447 salesforce_winter12_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/172/latest/en-us/sfdc/pdf/salesforce_winter12_release_notes.pdf
echo "24/447 salesforce_spring12_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/174/latest/en-us/sfdc/pdf/salesforce_spring12_release_notes.pdf
echo "25/447 salesforce_summer12_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/176/latest/en-us/sfdc/pdf/salesforce_summer12_release_notes.pdf
echo "26/447 salesforce_winter13_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/178/latest/en-us/sfdc/pdf/salesforce_winter13_release_notes.pdf
echo "27/447 salesforce_spring13_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/180/latest/en-us/sfdc/pdf/salesforce_spring13_release_notes.pdf
echo "28/447 salesforce_summer13_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/182/latest/en-us/sfdc/pdf/salesforce_summer13_release_notes.pdf
echo "29/447 salesforce_winter14_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/salesforce_winter14_release_notes.pdf
echo "30/447 salesforce_spring14_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/186/latest/en-us/sfdc/pdf/salesforce_spring14_release_notes.pdf
echo "31/447 salesforce_summer14_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/188/latest/en-us/sfdc/pdf/salesforce_summer14_release_notes.pdf
echo "32/447 salesforce_winter15_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/190/latest/en-us/sfdc/pdf/salesforce_winter15_release_notes.pdf
echo "33/447 salesforce_spring15_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/192/latest/en-us/sfdc/pdf/salesforce_spring15_release_notes.pdf
echo "34/447 salesforce_summer15_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/196/latest/en-us/sfdc/pdf/salesforce_summer15_release_notes.pdf
echo "35/447 salesforce_winter16_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/salesforce_winter16_release_notes.pdf
echo "36/447 salesforce_spring16_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_spring16_release_notes.pdf
echo "37/447 salesforce_summer16_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/202/latest/en-us/sfdc/pdf/salesforce_summer16_release_notes.pdf
echo "38/447 salesforce_winter17_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/204/latest/en-us/sfdc/pdf/salesforce_winter17_release_notes.pdf
echo "39/447 salesforce_spring17_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/206/latest/en-us/sfdc/pdf/salesforce_spring17_release_notes.pdf
echo "40/447 salesforce_summer17_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/salesforce_summer17_release_notes.pdf
echo "41/447 salesforce_winter18_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/210/latest/en-us/sfdc/pdf/salesforce_winter18_release_notes.pdf
echo "42/447 salesforce_spring18_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_spring18_release_notes.pdf
echo "43/447 salesforce_summer18_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/214/latest/en-us/sfdc/pdf/salesforce_summer18_release_notes.pdf
echo "44/447 salesforce_winter19_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/216/latest/en-us/sfdc/pdf/salesforce_winter19_release_notes.pdf
echo "45/447 salesforce_spring19_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/218/latest/en-us/sfdc/pdf/salesforce_spring19_release_notes.pdf
echo "46/447 salesforce_summer19_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/salesforce_summer19_release_notes.pdf
echo "47/447 salesforce_winter20_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/222/latest/en-us/sfdc/pdf/salesforce_winter20_release_notes.pdf
echo "48/447 salesforce_spring20_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_spring20_release_notes.pdf

# retired
echo "49/447 Lightning_Components_Cheatsheet.pdf"
curl -sLO https://developer.salesforce.com/resource/pdfs/Lightning_Components_Cheatsheet.pdf
echo "50/447 ot.pdf"
curl -sLO https://resources.docs.salesforce.com/136/latest/en-us/sfdc/pdf/ot.pdf
echo "51/447 sforce_API.pdf"
curl -sLO https://resources.docs.salesforce.com/138/latest/en-us/sfdc/pdf/sforce_API.pdf
echo "52/447 salesforce_axm_6.0_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/146/latest/en-us/sfdc/pdf/salesforce_axm_6.0_release_notes.pdf
echo "53/447 api_apex_rest.pdf"
curl -sLO https://resources.docs.salesforce.com/172/latest/en-us/sfdc/pdf/api_apex_rest.pdf
echo "54/447 dbcom_api_rest.pdf"
curl -sLO https://resources.docs.salesforce.com/174/latest/en-us/sfdc/pdf/dbcom_api_rest.pdf
echo "55/447 dbcom_api_streaming.pdf"
curl -sLO https://resources.docs.salesforce.com/176/latest/en-us/sfdc/pdf/dbcom_api_streaming.pdf
echo "56/447 dbcom_apex_language_reference.pdf"
curl -sLO https://resources.docs.salesforce.com/178/latest/en-us/sfdc/pdf/dbcom_apex_language_reference.pdf
echo "57/447 dbcom_chatter_rest_api.pdf"
curl -sLO https://resources.docs.salesforce.com/178/latest/en-us/sfdc/pdf/dbcom_chatter_rest_api.pdf
echo "58/447 dbcom_api_asynch.pdf"
curl -sLO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/dbcom_api_asynch.pdf
echo "59/447 dbcom_api_meta.pdf"
curl -sLO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/dbcom_api_meta.pdf
echo "60/447 forcecom_workbook.pdf"
curl -sLO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/forcecom_workbook.pdf
echo "61/447 integration_workbook.pdf"
curl -sLO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/integration_workbook.pdf
echo "62/447 salesforce_cti_developer_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/188/latest/en-us/sfdc/pdf/salesforce_cti_developer_guide.pdf
echo "63/447 salesforce_cti_developer_guide_2.pdf"
curl -sLO https://resources.docs.salesforce.com/188/latest/en-us/sfdc/pdf/salesforce_cti_developer_guide_2.pdf
echo "64/447 bi_dev_guide_eql.pdf"
curl -sLO https://resources.docs.salesforce.com/192/latest/en-us/sfdc/pdf/bi_dev_guide_eql.pdf
echo "65/447 salesforce_studio_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/192/latest/en-us/sfdc/pdf/salesforce_studio_cheatsheet.pdf
echo "66/447 record_locking_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/record_locking_cheatsheet.pdf
echo "67/447 salesforce1_guide_admin.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce1_guide_admin.pdf
echo "68/447 salesforce_appexchange_install_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_appexchange_install_guide.pdf
echo "69/447 salesforce_jigsaw_clean_user_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_jigsaw_clean_user_cheatsheet.pdf
echo "70/447 salesforce_profile_tabs_styleguide.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_profile_tabs_styleguide.pdf
echo "71/447 salesforce_query_search_optimization_developer_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_query_search_optimization_developer_cheatsheet.pdf
echo "72/447 service_communities_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/service_communities_guide.pdf
echo "73/447 wb_siteforce.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/wb_siteforce.pdf
echo "74/447 workbook_database.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/workbook_database.pdf
echo "75/447 salesforce1_api_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/196/latest/en-us/sfdc/pdf/salesforce1_api_guide.pdf
echo "76/447 salesforce_supported_browsers_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/196/latest/en-us/sfdc/pdf/salesforce_supported_browsers_cheatsheet.pdf
echo "77/447 apex_workbook.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/apex_workbook.pdf
echo "78/447 isv_pkg.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/isv_pkg.pdf
echo "79/447 lex_considerations.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/lex_considerations.pdf
echo "80/447 salesforce_knowledge_import_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/salesforce_knowledge_import_cheatsheet.pdf
echo "81/447 salesforce_knowledge_setup_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/salesforce_knowledge_setup_cheatsheet.pdf
echo "82/447 salesforce_pagelayouts_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/salesforce_pagelayouts_cheatsheet.pdf
echo "83/447 service_dev.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/service_dev.pdf
echo "84/447 salesforce_approvals_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_approvals_cheatsheet.pdf
echo "85/447 salesforce_email_approval_faq.pdf"
curl -sLO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_email_approval_faq.pdf
echo "86/447 salesforce_filtered_lookups_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_filtered_lookups_cheatsheet.pdf
echo "87/447 salesforce_web_integration_links.pdf"
curl -sLO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_web_integration_links.pdf
echo "88/447 salesforce_workflow_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_workflow_cheatsheet.pdf
echo "89/447 salesforce_importpersonal_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/202/latest/en-us/sfdc/pdf/salesforce_importpersonal_cheatsheet.pdf
echo "90/447 salesforce_recordtypes_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/202/latest/en-us/sfdc/pdf/salesforce_recordtypes_cheatsheet.pdf
echo "91/447 salesforce_workbench_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/202/latest/en-us/sfdc/pdf/salesforce_workbench_cheatsheet.pdf
echo "92/447 data_pipelines.pdf"
curl -sLO https://resources.docs.salesforce.com/204/latest/en-us/sfdc/pdf/data_pipelines.pdf
echo "93/447 salesforce_territories_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/206/latest/en-us/sfdc/pdf/salesforce_territories_implementation_guide.pdf
echo "94/447 tm_decision_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/206/latest/en-us/sfdc/pdf/tm_decision_guide.pdf
echo "95/447 sales_admins.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/sales_admins.pdf
echo "96/447 sales_users.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/sales_users.pdf
echo "97/447 support_admins.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/support_admins.pdf
echo "98/447 support_agents.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/support_agents.pdf
echo "99/447 workbook_analytics.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/workbook_analytics.pdf
echo "100/447 workbook_flow.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/workbook_flow.pdf
echo "101/447 workbook_security.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/workbook_security.pdf
echo "102/447 workbook_service_cloud.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/workbook_service_cloud.pdf
echo "103/447 workbook_vf.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/workbook_vf.pdf
echo "104/447 limits_limitations.pdf"
curl -sLO https://resources.docs.salesforce.com/210/latest/en-us/sfdc/pdf/limits_limitations.pdf
echo "105/447 salesforce_platform_mobile_services.pdf"
curl -sLO https://resources.docs.salesforce.com/210/latest/en-us/sfdc/pdf/salesforce_platform_mobile_services.pdf
echo "106/447 sf.pdf"
curl -sLO https://resources.docs.salesforce.com/210/latest/en-us/sfdc/pdf/sf.pdf
echo "107/447 salesforce_axm_blackberry_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_axm_blackberry_cheatsheet.pdf
echo "108/447 salesforce_axm_user_guide_for_blackberry.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_axm_user_guide_for_blackberry.pdf
echo "109/447 salesforce_cti_admin_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_cti_admin_cheatsheet.pdf
echo "110/447 salesforce_cti_demo_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_cti_demo_cheatsheet.pdf
echo "111/447 salesforce_cti_enduser_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_cti_enduser_cheatsheet.pdf
echo "112/447 salesforce_field_service_lightning_managed_package.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_field_service_lightning_managed_package.pdf
echo "113/447 salesforce_mobile_implementation.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_mobile_implementation.pdf
echo "114/447 salesforce_mobile_user_guide_android.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_mobile_user_guide_android.pdf
echo "115/447 salesforce_mobile_user_guide_for_iphone.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_mobile_user_guide_for_iphone.pdf
echo "116/447 sfdx_ide2.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/sfdx_ide2.pdf
echo "117/447 salesforce_communities_implementation.pdf"
curl -sLO https://resources.docs.salesforce.com/214/latest/en-us/sfdc/pdf/salesforce_communities_implementation.pdf
echo "118/447 salesforce_pubs_style_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/214/latest/en-us/sfdc/pdf/salesforce_pubs_style_guide.pdf
echo "119/447 salesforce_territories_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/214/latest/en-us/sfdc/pdf/salesforce_territories_cheatsheet.pdf
echo "120/447 pardot_get_start.pdf"
curl -sLO https://resources.docs.salesforce.com/216/latest/en-us/sfdc/pdf/pardot_get_start.pdf
echo "121/447 salesforce_report_builder_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/216/latest/en-us/sfdc/pdf/salesforce_report_builder_impl_guide.pdf
echo "122/447 salesforce_jigsaw_config.pdf"
curl -sLO https://resources.docs.salesforce.com/218/latest/en-us/sfdc/pdf/salesforce_jigsaw_config.pdf
echo "123/447 bi_admin_guide_data_integration_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/bi_admin_guide_data_integration_guide.pdf
echo "124/447 live_agent_administrator.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/live_agent_administrator.pdf
echo "125/447 live_agent_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/live_agent_dev_guide.pdf
echo "126/447 live_agent_rest.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/live_agent_rest.pdf
echo "127/447 live_agent_support_agents.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/live_agent_support_agents.pdf
echo "128/447 live_agent_support_supervisors.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/live_agent_support_supervisors.pdf
echo "129/447 salesforce1_admin_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/salesforce1_admin_guide.pdf
echo "130/447 salesforce_jigsaw_clean_admin_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/salesforce_jigsaw_clean_admin_cheatsheet.pdf
echo "131/447 salesforce_jigsaw_jfs_uninstall.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/salesforce_jigsaw_jfs_uninstall.pdf
echo "132/447 salesforce_vpm_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/salesforce_vpm_implementation_guide.pdf
echo "133/447 snapins.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/snapins.pdf
echo "134/447 snapins_web_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/snapins_web_dev_guide.pdf

# current
echo "135/447 BuddyMediaAnalytics.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaAnalytics.pdf
echo "136/447 BuddyMediaChannelAdminGuide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaChannelAdminGuide.pdf
echo "137/447 BuddyMediaConversationBuddy.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaConversationBuddy.pdf
echo "138/447 BuddyMediaDataAdapter.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaDataAdapter.pdf
echo "139/447 BuddyMediaDataAdaptorDeveloperGuide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaDataAdaptorDeveloperGuide.pdf
echo "140/447 BuddyMediaFacebookGlobalPages.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaFacebookGlobalPages.pdf
echo "141/447 BuddyMediaGettingStarted.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaGettingStarted.pdf
echo "142/447 BuddyMediaImplementationGuide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaImplementationGuide.pdf
echo "143/447 BuddyMediaProfileBuddy.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaProfileBuddy.pdf
echo "144/447 BuddyMediaReachBuddy.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaReachBuddy.pdf
echo "145/447 BuddyMediaYouTubeBrandChannels.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaYouTubeBrandChannels.pdf
echo "146/447 BuddyMediaYouTubeOneChannelFAQ.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaYouTubeOneChannelFAQ.pdf
echo "147/447 MarketingCloudBuddyMediaImplementationGuide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/MarketingCloudBuddyMediaImplementationGuide.pdf
echo "148/447 CheckoutUserGuide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/CheckoutUserGuide.pdf
echo "149/447 SF_Apex_Code_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Apex_Code_cheatsheet_web.pdf
echo "150/447 SF_CRM_Lightning_Experience_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_CRM_Lightning_Experience_web.pdf
echo "151/447 SF_CRM_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_CRM_cheatsheet_web.pdf
echo "152/447 SF_Custom_Metadata_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Custom_Metadata_cheatsheet_web.pdf
echo "153/447 SF_Formulas_Developer_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Formulas_Developer_cheatsheet_web.pdf
echo "154/447 SF_Git_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Git_cheatsheet_web.pdf
echo "155/447 SF_LightningComponents_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_LightningComponents_cheatsheet_web.pdf
echo "156/447 SF_Process_Automation_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Process_Automation_cheatsheet_web.pdf
echo "157/447 SF_Query_Search_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Query_Search_cheatsheet_web.pdf
echo "158/447 SF_Record-Locking-Cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Record-Locking-Cheatsheet_web.pdf
echo "159/447 SF_Reports_and_Dashboards_Rest_API_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Reports_and_Dashboards_Rest_API_web.pdf
echo "160/447 SF_Rest_API_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Rest_API_cheatsheet_web.pdf
echo "161/447 SF_S1-Admin_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_S1-Admin_cheatsheet_web.pdf
echo "162/447 SF_S1-Developer_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_S1-Developer_cheatsheet_web.pdf
echo "163/447 SF_Security_Admin_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Security_Admin_cheatsheet_web.pdf
echo "164/447 SF_Security_Developer_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Security_Developer_cheatsheet_web.pdf
echo "165/447 SF_Service_Cloud_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Service_Cloud_cheatsheet_web.pdf
echo "166/447 SF_Soap_API_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Soap_API_cheatsheet_web.pdf
echo "167/447 SF_Visualforce_Developer_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Visualforce_Developer_cheatsheet_web.pdf
echo "168/447 SK1_AbandonedCart.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK1_AbandonedCart.pdf
echo "169/447 SK2_CouponRedemption.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK2_CouponRedemption.pdf
echo "170/447 SK3_OrderonBehalfof.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK3_OrderonBehalfof.pdf
echo "171/447 SK4_PersonalizedMarketingRecommendations.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK4_PersonalizedMarketingRecommendations.pdf
echo "172/447 SK5_TransactionalEmails.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK5_TransactionalEmails.pdf
echo "173/447 SK6_CancelOrders.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK6_CancelOrders.pdf
echo "174/447 SK7_ConversationalCommerce.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK7_ConversationalCommerce.pdf
echo "175/447 SK8_SeamlessIdentity.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK8_SeamlessIdentity.pdf
echo "176/447 SK9_CrossCloudEngagementDataModels.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK9_CrossCloudEngagementDataModels.pdf
echo "177/447 chatter-edition-help.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/chatter-edition-help.pdf
echo "178/447 chatter-external.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/chatter-external.pdf
echo "179/447 chatter-help.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/chatter-help.pdf
echo "180/447 ext-svc-overview.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/ext-svc-overview.pdf
echo "181/447 field_service_lightning_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/field_service_lightning_guide.pdf
echo "182/447 identity_connect_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/identity_connect_impl_guide.pdf
echo "183/447 salesforce_query_search_optimization_developer_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/salesforce_query_search_optimization_developer_cheatsheet.pdf
echo "184/447 InsightsPartnerOverviews.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/InsightsPartnerOverviews.pdf
echo "185/447 MCNov13ReleaseNotes.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/MCNov13ReleaseNotes.pdf
echo "186/447 MCReleaseNotesSpring14.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/MCReleaseNotesSpring14.pdf
echo "187/447 MC_ReleaseNotes_August13.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/MC_ReleaseNotes_August13.pdf
echo "188/447 StreamActivityFAQ.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/StreamActivityFAQ.pdf
echo "189/447 MarketingCloudRadian6Introduction.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/MarketingCloudRadian6Introduction.pdf
echo "190/447 Radian6AnalysisDashboard.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6AnalysisDashboard.pdf
echo "191/447 Radian6EngagementConsole.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6EngagementConsole.pdf
echo "192/447 Radian6EngagementConsoleSpecifications.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6EngagementConsoleSpecifications.pdf
echo "193/447 Radian6FacebookManagedAccounts.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6FacebookManagedAccounts.pdf
echo "194/447 Radian6Insights.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6Insights.pdf
echo "195/447 Radian6Mobile.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6Mobile.pdf
echo "196/447 Radian6Reports.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6Reports.pdf
echo "197/447 Radian6SummaryDashboard.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6SummaryDashboard.pdf
echo "198/447 Radian6SuperUsers.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6SuperUsers.pdf
echo "199/447 Radian6TopicProfile.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6TopicProfile.pdf
echo "200/447 Radian6TopicProfileOptimization.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6TopicProfileOptimization.pdf
echo "201/447 Radian6TwitterManagedAccounts.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6TwitterManagedAccounts.pdf
echo "202/447 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/0/4/en-us/pdf/service_sdk_android.pdf
echo "203/447 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/1/2/en-us/pdf/service_sdk_ios.pdf
echo "204/447 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/2/0/en-us/pdf/service_sdk_ios.pdf
echo "205/447 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/206/0/en-us/pdf/service_sdk_android.pdf
echo "206/447 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/208/0/en-us/pdf/service_sdk_ios.pdf
echo "207/447 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/208/0/en-us/pdf/service_sdk_android.pdf
echo "208/447 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/210/0/en-us/pdf/service_sdk_ios.pdf
echo "209/447 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/210/0/en-us/pdf/service_sdk_android.pdf
echo "210/447 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/214/0/en-us/pdf/service_sdk_android.pdf
echo "211/447 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/214/0/en-us/pdf/service_sdk_ios.pdf
echo "212/447 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/218/0/en-us/pdf/service_sdk_ios.pdf
echo "213/447 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/218/0/en-us/pdf/service_sdk_android.pdf
echo "214/447 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/220/0/en-us/pdf/service_sdk_android.pdf
echo "215/447 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/220/0/en-us/pdf/service_sdk_ios.pdf
echo "216/447 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/222/0/en-us/pdf/service_sdk_android.pdf
echo "217/447 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/222/0/en-us/pdf/service_sdk_ios.pdf
echo "218/447 apex_ajax.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/apex_ajax.pdf
echo "219/447 apex_api.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/apex_api.pdf
echo "220/447 api_action.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_action.pdf
echo "221/447 api_asynch.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_asynch.pdf
echo "222/447 api_bulk_v2.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_bulk_v2.pdf
echo "223/447 api_console.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_console.pdf
echo "224/447 api_cti.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_cti.pdf
echo "225/447 api_meta.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_meta.pdf
echo "226/447 api_rest.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_rest.pdf
echo "227/447 api_rest_industries.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_rest_industries.pdf
echo "228/447 api_social.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_social.pdf
echo "229/447 api_streaming.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_streaming.pdf
echo "230/447 api_tooling.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_tooling.pdf
echo "231/447 api_ui.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_ui.pdf
echo "232/447 appexchange_install_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/appexchange_install_guide.pdf
echo "233/447 appexchange_publishing_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/appexchange_publishing_guide.pdf
echo "234/447 apps.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/apps.pdf
echo "235/447 async_soql_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/async_soql_guide.pdf
echo "236/447 basics.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/basics.pdf
echo "237/447 bi_admin_guide_security.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_admin_guide_security.pdf
echo "238/447 bi_admin_guide_setup.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_admin_guide_setup.pdf
echo "239/447 bi_dev_guide_bindings.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_bindings.pdf
echo "240/447 bi_dev_guide_ext_data.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_ext_data.pdf
echo "241/447 bi_dev_guide_ext_data_format.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_ext_data_format.pdf
echo "242/447 bi_dev_guide_json.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_json.pdf
echo "243/447 bi_dev_guide_rest.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_rest.pdf
echo "244/447 bi_dev_guide_saql.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_saql.pdf
echo "245/447 bi_dev_guide_sdk.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_sdk.pdf
echo "246/447 bi_dev_guide_wave_templates.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_wave_templates.pdf
echo "247/447 bi_dev_guide_xmd.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_xmd.pdf
echo "248/447 big_objects_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/big_objects_guide.pdf
echo "249/447 canvas_framework.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/canvas_framework.pdf
echo "250/447 case_feed_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/case_feed_dev_guide.pdf
echo "251/447 chatter.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/chatter.pdf
echo "252/447 collaboration.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/collaboration.pdf
echo "253/447 collaboration_admin.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/collaboration_admin.pdf
echo "254/447 communities.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/communities.pdf
echo "255/447 communities_dev.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/communities_dev.pdf
echo "256/447 community_templates.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/community_templates.pdf
echo "257/447 console.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/console.pdf
echo "258/447 custom_metadata_types_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/custom_metadata_types_impl_guide.pdf
echo "259/447 data_dot_com_clean_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/data_dot_com_clean_impl_guide.pdf
echo "260/447 datacom_salesforce_record_matching.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/datacom_salesforce_record_matching.pdf
echo "261/447 datadotcom_api_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/datadotcom_api_dev_guide.pdf
echo "262/447 deploy_sandboxes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/deploy_sandboxes.pdf
echo "263/447 draes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/draes.pdf
echo "264/447 eclipse.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/eclipse.pdf
echo "265/447 einstein_platform_services.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/einstein_platform_services.pdf
echo "266/447 extend_click.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/extend_click.pdf
echo "267/447 extend_code.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/extend_code.pdf
echo "268/447 federated_search.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/federated_search.pdf
echo "269/447 field_history_retention.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/field_history_retention.pdf
echo "270/447 financial_services.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/financial_services.pdf
echo "271/447 forecasts.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/forecasts.pdf
echo "272/447 formula_date_time_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/formula_date_time_tipsheet.pdf
echo "273/447 fsc_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/fsc_dev_guide.pdf
echo "274/447 generate_orders_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/generate_orders_implementation_guide.pdf
echo "275/447 health_cloud_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/health_cloud_dev_guide.pdf
echo "276/447 healthcare.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/healthcare.pdf
echo "277/447 integration_patterns_and_practices.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/integration_patterns_and_practices.pdf
echo "278/447 jsapi_chatteranswers.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/jsapi_chatteranswers.pdf
echo "279/447 lex.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/lex.pdf
echo "280/447 lightning.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/lightning.pdf
echo "281/447 lightning_adoption_javascript_button_conversion.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/lightning_adoption_javascript_button_conversion.pdf
echo "282/447 lightning_experience_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/lightning_experience_guide.pdf
echo "283/447 lightning_knowledge_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/lightning_knowledge_guide.pdf
echo "284/447 mobile_sdk.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/mobile_sdk.pdf
echo "285/447 object_reference.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/object_reference.pdf
echo "286/447 oem_user_license_comparison_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/oem_user_license_comparison_tipsheet.pdf
echo "287/447 omnichannel_supervisor.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/omnichannel_supervisor.pdf
echo "288/447 organization_sync.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/organization_sync.pdf
echo "289/447 platform_events.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/platform_events.pdf
echo "290/447 sales_einstein_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sales_einstein_implementation_guide.pdf
echo "291/447 salesforce1_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_guide.pdf
echo "292/447 salesforce1_mobile_security.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_mobile_security.pdf
echo "293/447 salesforce1_url_schemes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_url_schemes.pdf
echo "294/447 salesforce1_user_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_user_guide.pdf
echo "295/447 salesforce_B2C_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_B2C_implementation_guide.pdf
echo "296/447 salesforce_HTMLtemplates_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_HTMLtemplates_cheatsheet.pdf
echo "297/447 salesforce_TEadmin_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_TEadmin_cheatsheet.pdf
echo "298/447 salesforce_TEuser_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_TEuser_cheatsheet.pdf
echo "299/447 salesforce_agent_console_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_agent_console_cheatsheet.pdf
echo "300/447 salesforce_analytics_folder_sharing_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_analytics_folder_sharing_cheatsheet.pdf
echo "301/447 salesforce_analytics_overview_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_analytics_overview_cheatsheet.pdf
echo "302/447 salesforce_analytics_rest_api.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_analytics_rest_api.pdf
echo "303/447 salesforce_answers_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_answers_implementation_guide.pdf
echo "304/447 salesforce_apex_language_reference.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_apex_language_reference.pdf
echo "305/447 salesforce_app_limits_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_app_limits_cheatsheet.pdf
echo "306/447 salesforce_assets_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_assets_cheatsheet.pdf
echo "307/447 salesforce_busprocess_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_busprocess_cheatsheet.pdf
echo "308/447 salesforce_campaign_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_campaign_implementation_guide.pdf
echo "309/447 salesforce_campaigns_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_campaigns_cheatsheet.pdf
echo "310/447 salesforce_case_feed_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_case_feed_cheatsheet.pdf
echo "311/447 salesforce_case_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_case_implementation_guide.pdf
echo "312/447 salesforce_case_interaction_setup_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_case_interaction_setup_cheatsheet.pdf
echo "313/447 salesforce_chatter_rest_api.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_chatter_rest_api.pdf
echo "314/447 salesforce_chatterplus_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_chatterplus_tipsheet.pdf
echo "315/447 salesforce_client_autoupdate_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_client_autoupdate_cheatsheet.pdf
echo "316/447 salesforce_communities_managers_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_communities_managers_guide.pdf
echo "317/447 salesforce_community_identity_templates.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_community_identity_templates.pdf
echo "318/447 salesforce_conflict_res_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_conflict_res_cheatsheet.pdf
echo "319/447 salesforce_console_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_console_impl_guide.pdf
echo "320/447 salesforce_content_delivery_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_content_delivery_cheatsheet.pdf
echo "321/447 salesforce_content_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_content_implementation_guide.pdf
echo "322/447 salesforce_convertleads_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_convertleads_cheatsheet.pdf
echo "323/447 salesforce_creating_on_demand_apps.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_creating_on_demand_apps.pdf
echo "324/447 salesforce_customer_portal_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_customer_portal_implementation_guide.pdf
echo "325/447 salesforce_dashboard_filters_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_dashboard_filters_cheatsheet.pdf
echo "326/447 salesforce_dashboard_samples.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_dashboard_samples.pdf
echo "327/447 salesforce_dashboards_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_dashboards_cheatsheet.pdf
echo "328/447 salesforce_data_import_wizard_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_data_import_wizard_tipsheet.pdf
echo "329/447 salesforce_data_loader.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_data_loader.pdf
echo "330/447 salesforce_data_quality_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_data_quality_cheatsheet.pdf
echo "331/447 salesforce_data_quality_duplicate_prevention.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_data_quality_duplicate_prevention.pdf
echo "332/447 salesforce_defer_sharing_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_defer_sharing_tipsheet.pdf
echo "333/447 salesforce_developer_environment_dotnet_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_developer_environment_dotnet_tipsheet.pdf
echo "334/447 salesforce_developer_environment_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_developer_environment_tipsheet.pdf
echo "335/447 salesforce_development_lifecycle.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_development_lifecycle.pdf
echo "336/447 salesforce_divisions_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_divisions_cheatsheet.pdf
echo "337/447 salesforce_dynamic_dashboards_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_dynamic_dashboards_cheatsheet.pdf
echo "338/447 salesforce_ee_upgrade_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_ee_upgrade_guide.pdf
echo "339/447 salesforce_entitlements_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_entitlements_implementation_guide.pdf
echo "340/447 salesforce_exchange_sync_admin_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_exchange_sync_admin_implementation_guide.pdf
echo "341/447 salesforce_exchange_sync_user.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_exchange_sync_user.pdf
echo "342/447 salesforce_external_identity_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_external_identity_implementation_guide.pdf
echo "343/447 salesforce_field_names_reference.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_field_names_reference.pdf
echo "344/447 salesforce_file_sync_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_file_sync_impl_guide.pdf
echo "345/447 salesforce_files_connect_implementation.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_files_connect_implementation.pdf
echo "346/447 salesforce_finserv_admin_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_admin_guide.pdf
echo "347/447 salesforce_finserv_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_impl_guide.pdf
echo "348/447 salesforce_finserv_install_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_install_guide.pdf
echo "349/447 salesforce_finserv_quick_start.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_quick_start.pdf
echo "350/447 salesforce_finserv_upgrade_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_upgrade_guide.pdf
echo "351/447 salesforce_flash_builder.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_flash_builder.pdf
echo "352/447 salesforce_flash_builder_quickstart.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_flash_builder_quickstart.pdf
echo "353/447 salesforce_forecastFAQ_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_forecastFAQ_cheatsheet.pdf
echo "354/447 salesforce_forecastsetup_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_forecastsetup_cheatsheet.pdf
echo "355/447 salesforce_forecastuser_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_forecastuser_cheatsheet.pdf
echo "356/447 salesforce_formula_size_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_formula_size_tipsheet.pdf
echo "357/447 salesforce_formulas_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_formulas_cheatsheet.pdf
echo "358/447 salesforce_groupcal_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_groupcal_cheatsheet.pdf
echo "359/447 salesforce_guided_engagement.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_guided_engagement.pdf
echo "360/447 salesforce_health_cloud_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_health_cloud_impl_guide.pdf
echo "361/447 salesforce_ideas_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_ideas_cheatsheet.pdf
echo "362/447 salesforce_ideas_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_ideas_implementation_guide.pdf
echo "363/447 salesforce_ideas_theme_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_ideas_theme_cheatsheet.pdf
echo "364/447 salesforce_identity_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_identity_implementation_guide.pdf
echo "365/447 salesforce_implementing_territory_mgmt2_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_implementing_territory_mgmt2_guide.pdf
echo "366/447 salesforce_import_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_import_cheatsheet.pdf
echo "367/447 salesforce_knowledge_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_knowledge_dev_guide.pdf
echo "368/447 salesforce_knowledge_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_knowledge_implementation_guide.pdf
echo "369/447 salesforce_large_data_volumes_bp.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_large_data_volumes_bp.pdf
echo "370/447 salesforce_lead_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_lead_implementation_guide.pdf
echo "371/447 salesforce_leads_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_leads_cheatsheet.pdf
echo "372/447 salesforce_limits_practices.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_limits_practices.pdf
echo "373/447 salesforce_lma_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_lma_guide.pdf
echo "374/447 salesforce_mailmerge.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_mailmerge.pdf
echo "375/447 salesforce_mailmerge_upload_guidelines.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_mailmerge_upload_guidelines.pdf
echo "376/447 salesforce_massdelete_undoimport.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_massdelete_undoimport.pdf
echo "377/447 salesforce_migration_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_migration_guide.pdf
echo "378/447 salesforce_mobile_push_notifications_implementation.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_mobile_push_notifications_implementation.pdf
echo "379/447 salesforce_office_edition_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_office_edition_cheatsheet.pdf
echo "380/447 salesforce_office_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_office_release_notes.pdf
echo "381/447 salesforce_offline_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_offline_cheatsheet.pdf
echo "382/447 salesforce_offline_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_offline_release_notes.pdf
echo "383/447 salesforce_opportunity_trending_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_opportunity_trending_cheatsheet.pdf
echo "384/447 salesforce_orders_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_orders_cheatsheet.pdf
echo "385/447 salesforce_packaging_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_packaging_guide.pdf
echo "386/447 salesforce_pages_developers_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_pages_developers_guide.pdf
echo "387/447 salesforce_partner_portal_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_partner_portal_guide.pdf
echo "388/447 salesforce_placeorder_rest_api.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_placeorder_rest_api.pdf
echo "389/447 salesforce_platform_encryption_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_platform_encryption_implementation_guide.pdf
echo "390/447 salesforce_platform_encryption_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_platform_encryption_tipsheet.pdf
echo "391/447 salesforce_platform_glossary.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_platform_glossary.pdf
echo "392/447 salesforce_platform_portal_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_platform_portal_implementation_guide.pdf
echo "393/447 salesforce_portal_to_community_migration_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_portal_to_community_migration_cheatsheet.pdf
echo "394/447 salesforce_products_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_products_cheatsheet.pdf
echo "395/447 salesforce_profile_tabs_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_profile_tabs_cheatsheet.pdf
echo "396/447 salesforce_questions_portal_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_questions_portal_implementation_guide.pdf
echo "397/447 salesforce_record_access_under_the_hood.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_record_access_under_the_hood.pdf
echo "398/447 salesforce_relgroups_getstart.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_relgroups_getstart.pdf
echo "399/447 salesforce_report_cross_filters_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_report_cross_filters_cheatsheet.pdf
echo "400/447 salesforce_report_joined_format_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_report_joined_format_cheatsheet.pdf
echo "401/447 salesforce_report_summary_functions_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_report_summary_functions_cheatsheet.pdf
echo "402/447 salesforce_reportperformance_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_reportperformance_cheatsheet.pdf
echo "403/447 salesforce_reports_bucketing_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_reports_bucketing_cheatsheet.pdf
echo "404/447 salesforce_reports_enhanced_reports_tab_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_reports_enhanced_reports_tab_tipsheet.pdf
echo "405/447 salesforce_reports_schedule_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_reports_schedule_cheatsheet.pdf
echo "406/447 salesforce_salesrep_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_salesrep_cheatsheet.pdf
echo "407/447 salesforce_security_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_security_impl_guide.pdf
echo "408/447 salesforce_selfservice_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_selfservice_cheatsheet.pdf
echo "409/447 salesforce_selfservice_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_selfservice_implementation_guide.pdf
echo "410/447 salesforce_sfo_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_sfo_release_notes.pdf
echo "411/447 salesforce_sharing_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_sharing_cheatsheet.pdf
echo "412/447 salesforce_sharing_users_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_sharing_users_tipsheet.pdf
echo "413/447 salesforce_single_sign_on.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_single_sign_on.pdf
echo "414/447 salesforce_solutions_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_solutions_cheatsheet.pdf
echo "415/447 salesforce_solutions_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_solutions_implementation_guide.pdf
echo "416/447 salesforce_soql_sosl.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_soql_sosl.pdf
echo "417/447 salesforce_supportadmin_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_supportadmin_cheatsheet.pdf
echo "418/447 salesforce_supportrep_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_supportrep_cheatsheet.pdf
echo "419/447 salesforce_technical_requirements.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_technical_requirements.pdf
echo "420/447 salesforce_useful_approval_processes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_useful_approval_processes.pdf
echo "421/447 salesforce_useful_formula_fields.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_useful_formula_fields.pdf
echo "422/447 salesforce_useful_validation_formulas.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_useful_validation_formulas.pdf
echo "423/447 salesforce_useful_workflow_rules.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_useful_workflow_rules.pdf
echo "424/447 salesforce_using_multiple_currencies.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_using_multiple_currencies.pdf
echo "425/447 salesforce_views_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_views_cheatsheet.pdf
echo "426/447 salesforce_visualforce_best_practices.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_visualforce_best_practices.pdf
echo "427/447 salesforce_voice_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_voice_implementation_guide.pdf
echo "428/447 salesforce_wm_peripherals_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_wm_peripherals_implementation_guide.pdf
echo "429/447 secure_coding.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/secure_coding.pdf
echo "430/447 security_certificate_changes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/security_certificate_changes.pdf
echo "431/447 service_presence_administrators.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/service_presence_administrators.pdf
echo "432/447 service_presence_developer_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/service_presence_developer_guide.pdf
echo "433/447 setup.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/setup.pdf
echo "434/447 sfdx_cli_reference.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sfdx_cli_reference.pdf
echo "435/447 sfdx_dev.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sfdx_dev.pdf
echo "436/447 sfdx_setup.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sfdx_setup.pdf
echo "437/447 sfo_getting_started_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sfo_getting_started_guide.pdf
echo "438/447 sharing_architecture.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sharing_architecture.pdf
echo "439/447 smb_sales_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/smb_sales_impl_guide.pdf
echo "440/447 smb_sales_impl_guide_2.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/smb_sales_impl_guide_2.pdf
echo "441/447 social_customer_service_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/social_customer_service_impl_guide.pdf
echo "442/447 sos_administrators.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sos_administrators.pdf
echo "443/447 state_country_picklists_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/state_country_picklists_impl_guide.pdf
echo "444/447 support.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/support.pdf
echo "445/447 team_selling_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/team_selling_implementation_guide.pdf
echo "446/447 utility_bar_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/utility_bar_impl_guide.pdf
echo "447/447 workcom_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/workcom_implementation_guide.pdf
echo "Done"
