#!/bin/sh
mkdir -p pdfs
cd pdfs
mkdir -p 224
cd 224

# release notes
echo "1/448 salesforce_winter04_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_winter04_release_notes.pdf
echo "2/448 salesforce_spring04_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_spring04_release_notes.pdf
echo "3/448 salesforce_summer04_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_summer04_release_notes.pdf
echo "4/448 salesforce_winter05_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_winter05_release_notes.pdf
echo "5/448 salesforce_summer05_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_summer05_release_notes.pdf
echo "6/448 salesforce_winter06_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_winter06_release_notes.pdf
echo "7/448 salesforce_summer06_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/142/latest/en-us/sfdc/pdf/salesforce_summer06_release_notes.pdf
echo "8/448 salesforce_winter07_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/144/latest/en-us/sfdc/pdf/salesforce_winter07_release_notes.pdf
echo "9/448 salesforce_spring07_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/144/latest/en-us/sfdc/pdf/salesforce_spring07_release_notes.pdf
echo "10/448 salesforce_summer07_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/146/latest/en-us/sfdc/pdf/salesforce_summer07_release_notes.pdf
echo "11/448 salesforce_winter08_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/148/latest/en-us/sfdc/pdf/salesforce_winter08_release_notes.pdf
echo "12/448 salesforce_spring08_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/150/latest/en-us/sfdc/pdf/salesforce_spring08_release_notes.pdf
echo "13/448 salesforce_summer08_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/152/latest/en-us/sfdc/pdf/salesforce_summer08_release_notes.pdf
echo "14/448 salesforce_winter09_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/154/latest/en-us/sfdc/pdf/salesforce_winter09_release_notes.pdf
echo "15/448 salesforce_spring09_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/156/latest/en-us/sfdc/pdf/salesforce_spring09_release_notes.pdf
echo "16/448 salesforce_summer09_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/158/latest/en-us/sfdc/pdf/salesforce_summer09_release_notes.pdf
echo "17/448 salesforce_winter10_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/160/latest/en-us/sfdc/pdf/salesforce_winter10_release_notes.pdf
echo "18/448 salesforce_spring10_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/162/latest/en-us/sfdc/pdf/salesforce_spring10_release_notes.pdf
echo "19/448 salesforce_summer10_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/164/latest/en-us/sfdc/pdf/salesforce_summer10_release_notes.pdf
echo "20/448 salesforce_winter11_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/166/latest/en-us/sfdc/pdf/salesforce_winter11_release_notes.pdf
echo "21/448 salesforce_spring11_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/168/latest/en-us/sfdc/pdf/salesforce_spring11_release_notes.pdf
echo "22/448 salesforce_summer11_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/170/latest/en-us/sfdc/pdf/salesforce_summer11_release_notes.pdf
echo "23/448 salesforce_winter12_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/172/latest/en-us/sfdc/pdf/salesforce_winter12_release_notes.pdf
echo "24/448 salesforce_spring12_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/174/latest/en-us/sfdc/pdf/salesforce_spring12_release_notes.pdf
echo "25/448 salesforce_summer12_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/176/latest/en-us/sfdc/pdf/salesforce_summer12_release_notes.pdf
echo "26/448 salesforce_winter13_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/178/latest/en-us/sfdc/pdf/salesforce_winter13_release_notes.pdf
echo "27/448 salesforce_spring13_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/180/latest/en-us/sfdc/pdf/salesforce_spring13_release_notes.pdf
echo "28/448 salesforce_summer13_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/182/latest/en-us/sfdc/pdf/salesforce_summer13_release_notes.pdf
echo "29/448 salesforce_winter14_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/salesforce_winter14_release_notes.pdf
echo "30/448 salesforce_spring14_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/186/latest/en-us/sfdc/pdf/salesforce_spring14_release_notes.pdf
echo "31/448 salesforce_summer14_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/188/latest/en-us/sfdc/pdf/salesforce_summer14_release_notes.pdf
echo "32/448 salesforce_winter15_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/190/latest/en-us/sfdc/pdf/salesforce_winter15_release_notes.pdf
echo "33/448 salesforce_spring15_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/192/latest/en-us/sfdc/pdf/salesforce_spring15_release_notes.pdf
echo "34/448 salesforce_summer15_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/196/latest/en-us/sfdc/pdf/salesforce_summer15_release_notes.pdf
echo "35/448 salesforce_winter16_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/salesforce_winter16_release_notes.pdf
echo "36/448 salesforce_spring16_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_spring16_release_notes.pdf
echo "37/448 salesforce_summer16_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/202/latest/en-us/sfdc/pdf/salesforce_summer16_release_notes.pdf
echo "38/448 salesforce_winter17_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/204/latest/en-us/sfdc/pdf/salesforce_winter17_release_notes.pdf
echo "39/448 salesforce_spring17_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/206/latest/en-us/sfdc/pdf/salesforce_spring17_release_notes.pdf
echo "40/448 salesforce_summer17_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/salesforce_summer17_release_notes.pdf
echo "41/448 salesforce_winter18_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/210/latest/en-us/sfdc/pdf/salesforce_winter18_release_notes.pdf
echo "42/448 salesforce_spring18_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_spring18_release_notes.pdf
echo "43/448 salesforce_summer18_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/214/latest/en-us/sfdc/pdf/salesforce_summer18_release_notes.pdf
echo "44/448 salesforce_winter19_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/216/latest/en-us/sfdc/pdf/salesforce_winter19_release_notes.pdf
echo "45/448 salesforce_spring19_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/218/latest/en-us/sfdc/pdf/salesforce_spring19_release_notes.pdf
echo "46/448 salesforce_summer19_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/salesforce_summer19_release_notes.pdf
echo "47/448 salesforce_winter20_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/222/latest/en-us/sfdc/pdf/salesforce_winter20_release_notes.pdf
echo "48/448 salesforce_spring20_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_spring20_release_notes.pdf
echo "49/448 salesforce_summer20_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/226/latest/en-us/sfdc/pdf/salesforce_summer20_release_notes.pdf

# retired
echo "49/448 Lightning_Components_Cheatsheet.pdf"
curl -sLO https://developer.salesforce.com/resource/pdfs/Lightning_Components_Cheatsheet.pdf
echo "50/448 ot.pdf"
curl -sLO https://resources.docs.salesforce.com/136/latest/en-us/sfdc/pdf/ot.pdf
echo "51/448 sforce_API.pdf"
curl -sLO https://resources.docs.salesforce.com/138/latest/en-us/sfdc/pdf/sforce_API.pdf
echo "52/448 salesforce_axm_6.0_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/146/latest/en-us/sfdc/pdf/salesforce_axm_6.0_release_notes.pdf
echo "53/448 api_apex_rest.pdf"
curl -sLO https://resources.docs.salesforce.com/172/latest/en-us/sfdc/pdf/api_apex_rest.pdf
echo "54/448 dbcom_api_rest.pdf"
curl -sLO https://resources.docs.salesforce.com/174/latest/en-us/sfdc/pdf/dbcom_api_rest.pdf
echo "55/448 dbcom_api_streaming.pdf"
curl -sLO https://resources.docs.salesforce.com/176/latest/en-us/sfdc/pdf/dbcom_api_streaming.pdf
echo "56/448 dbcom_apex_language_reference.pdf"
curl -sLO https://resources.docs.salesforce.com/178/latest/en-us/sfdc/pdf/dbcom_apex_language_reference.pdf
echo "57/448 dbcom_chatter_rest_api.pdf"
curl -sLO https://resources.docs.salesforce.com/178/latest/en-us/sfdc/pdf/dbcom_chatter_rest_api.pdf
echo "58/448 dbcom_api_asynch.pdf"
curl -sLO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/dbcom_api_asynch.pdf
echo "59/448 dbcom_api_meta.pdf"
curl -sLO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/dbcom_api_meta.pdf
echo "60/448 forcecom_workbook.pdf"
curl -sLO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/forcecom_workbook.pdf
echo "61/448 integration_workbook.pdf"
curl -sLO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/integration_workbook.pdf
echo "62/448 workbook_analytics.pdf"
curl -sLO https://resources.docs.salesforce.com/184/latest/en-us/sfdc/pdf/workbook_analytics.pdf
echo "63/448 salesforce_cti_developer_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/188/latest/en-us/sfdc/pdf/salesforce_cti_developer_guide.pdf
echo "64/448 salesforce_cti_developer_guide_2.pdf"
curl -sLO https://resources.docs.salesforce.com/188/latest/en-us/sfdc/pdf/salesforce_cti_developer_guide_2.pdf
echo "65/448 bi_dev_guide_eql.pdf"
curl -sLO https://resources.docs.salesforce.com/192/latest/en-us/sfdc/pdf/bi_dev_guide_eql.pdf
echo "66/448 salesforce_studio_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/192/latest/en-us/sfdc/pdf/salesforce_studio_cheatsheet.pdf
echo "67/448 record_locking_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/record_locking_cheatsheet.pdf
echo "68/448 salesforce1_guide_admin.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce1_guide_admin.pdf
echo "69/448 salesforce_appexchange_install_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_appexchange_install_guide.pdf
echo "70/448 salesforce_jigsaw_clean_user_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_jigsaw_clean_user_cheatsheet.pdf
echo "71/448 salesforce_profile_tabs_styleguide.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_profile_tabs_styleguide.pdf
echo "72/448 salesforce_query_search_optimization_developer_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/salesforce_query_search_optimization_developer_cheatsheet.pdf
echo "73/448 service_communities_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/service_communities_guide.pdf
echo "74/448 wb_siteforce.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/wb_siteforce.pdf
echo "75/448 workbook_database.pdf"
curl -sLO https://resources.docs.salesforce.com/194/latest/en-us/sfdc/pdf/workbook_database.pdf
echo "76/448 salesforce1_api_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/196/latest/en-us/sfdc/pdf/salesforce1_api_guide.pdf
echo "77/448 salesforce_supported_browsers_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/196/latest/en-us/sfdc/pdf/salesforce_supported_browsers_cheatsheet.pdf
echo "78/448 apex_workbook.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/apex_workbook.pdf
echo "79/448 community_templates.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/community_templates.pdf
echo "80/448 isv_pkg.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/isv_pkg.pdf
echo "81/448 lex_considerations.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/lex_considerations.pdf
echo "82/448 salesforce_development_lifecycle.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/salesforce_development_lifecycle.pdf
echo "83/448 salesforce_knowledge_import_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/salesforce_knowledge_import_cheatsheet.pdf
echo "84/448 salesforce_knowledge_setup_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/salesforce_knowledge_setup_cheatsheet.pdf
echo "85/448 salesforce_pagelayouts_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/salesforce_pagelayouts_cheatsheet.pdf
echo "86/448 salesforce_sfo_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/salesforce_sfo_release_notes.pdf
echo "87/448 service_dev.pdf"
curl -sLO https://resources.docs.salesforce.com/198/latest/en-us/sfdc/pdf/service_dev.pdf
echo "88/448 salesforce_approvals_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_approvals_cheatsheet.pdf
echo "89/448 salesforce_email_approval_faq.pdf"
curl -sLO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_email_approval_faq.pdf
echo "90/448 salesforce_filtered_lookups_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_filtered_lookups_cheatsheet.pdf
echo "91/448 salesforce_web_integration_links.pdf"
curl -sLO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_web_integration_links.pdf
echo "92/448 salesforce_workflow_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/200/latest/en-us/sfdc/pdf/salesforce_workflow_cheatsheet.pdf
echo "93/448 salesforce_importpersonal_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/202/latest/en-us/sfdc/pdf/salesforce_importpersonal_cheatsheet.pdf
echo "94/448 salesforce_recordtypes_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/202/latest/en-us/sfdc/pdf/salesforce_recordtypes_cheatsheet.pdf
echo "95/448 salesforce_workbench_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/202/latest/en-us/sfdc/pdf/salesforce_workbench_cheatsheet.pdf
echo "96/448 data_pipelines.pdf"
curl -sLO https://resources.docs.salesforce.com/204/latest/en-us/sfdc/pdf/data_pipelines.pdf
echo "97/448 salesforce_finserv_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/204/latest/en-us/sfdc/pdf/salesforce_finserv_impl_guide.pdf
echo "98/448 salesforce_territories_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/206/latest/en-us/sfdc/pdf/salesforce_territories_implementation_guide.pdf
echo "99/448 tm_decision_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/206/latest/en-us/sfdc/pdf/tm_decision_guide.pdf
echo "100/448 sales_admins.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/sales_admins.pdf
echo "101/448 sales_users.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/sales_users.pdf
echo "102/448 support_admins.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/support_admins.pdf
echo "103/448 support_agents.pdf"
curl -sLO https://resources.docs.salesforce.com/208/latest/en-us/sfdc/pdf/support_agents.pdf
echo "104/448 workbook_flow.pdf"
curl -sLO https://blog.bessereau.eu/assets/pdfs/workbook_flow.pdf
echo "105/448 workbook_security.pdf"
curl -sLO https://web.archive.org/web/20150921195311/https://resources.docs.salesforce.com/sfdc/pdf/workbook_security.pdf
echo "106/448 workbook_service_cloud.pdf"
curl -sLO https://www.audentia-gestion.fr/salesforce/workbook_service_cloud.pdf
echo "107/448 workbook_vf.pdf"
curl -sLO https://www.audentia-gestion.fr/salesforce/workbook_vf.pdf
echo "108/448 limits_limitations.pdf"
curl -sLO https://resources.docs.salesforce.com/210/latest/en-us/sfdc/pdf/limits_limitations.pdf
echo "109/448 salesforce_platform_mobile_services.pdf"
curl -sLO https://resources.docs.salesforce.com/210/latest/en-us/sfdc/pdf/salesforce_platform_mobile_services.pdf
echo "110/448 sf.pdf"
curl -sLO https://resources.docs.salesforce.com/210/latest/en-us/sfdc/pdf/sf.pdf
echo "111/448 salesforce_axm_blackberry_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_axm_blackberry_cheatsheet.pdf
echo "112/448 salesforce_axm_user_guide_for_blackberry.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_axm_user_guide_for_blackberry.pdf
echo "113/448 salesforce_cti_admin_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_cti_admin_cheatsheet.pdf
echo "114/448 salesforce_cti_demo_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_cti_demo_cheatsheet.pdf
echo "115/448 salesforce_cti_enduser_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_cti_enduser_cheatsheet.pdf
echo "116/448 salesforce_field_service_lightning_managed_package.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_field_service_lightning_managed_package.pdf
echo "117/448 salesforce_mobile_implementation.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_mobile_implementation.pdf
echo "118/448 salesforce_mobile_user_guide_android.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_mobile_user_guide_android.pdf
echo "119/448 salesforce_mobile_user_guide_for_iphone.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/salesforce_mobile_user_guide_for_iphone.pdf
echo "120/448 sfdx_ide2.pdf"
curl -sLO https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/sfdx_ide2.pdf
echo "121/448 salesforce_communities_implementation.pdf"
curl -sLO https://www.audentia-gestion.fr/salesforce/salesforce_communities_implementation.pdf
echo "122/448 salesforce_creating_on_demand_apps.pdf"
curl -sLO https://resources.docs.salesforce.com/214/latest/en-us/sfdc/pdf/salesforce_creating_on_demand_apps.pdf
echo "123/448 salesforce_pubs_style_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/214/latest/en-us/sfdc/pdf/salesforce_pubs_style_guide.pdf
echo "124/448 salesforce_territories_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/214/latest/en-us/sfdc/pdf/salesforce_territories_cheatsheet.pdf
echo "125/448 pardot_get_start.pdf"
curl -sLO https://resources.docs.salesforce.com/216/latest/en-us/sfdc/pdf/pardot_get_start.pdf
echo "126/448 salesforce_report_builder_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/216/latest/en-us/sfdc/pdf/salesforce_report_builder_impl_guide.pdf
echo "127/448 salesforce_jigsaw_config.pdf"
curl -sLO https://resources.docs.salesforce.com/218/latest/en-us/sfdc/pdf/salesforce_jigsaw_config.pdf
echo "128/448 bi_admin_guide_data_integration_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/bi_admin_guide_data_integration_guide.pdf
echo "129/448 live_agent_administrator.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/live_agent_administrator.pdf
echo "130/448 live_agent_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/live_agent_dev_guide.pdf
echo "131/448 live_agent_rest.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/live_agent_rest.pdf
echo "132/448 live_agent_support_agents.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/live_agent_support_agents.pdf
echo "133/448 live_agent_support_supervisors.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/live_agent_support_supervisors.pdf
echo "134/448 salesforce1_admin_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/salesforce1_admin_guide.pdf
echo "135/448 salesforce_jigsaw_clean_admin_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/salesforce_jigsaw_clean_admin_cheatsheet.pdf
echo "136/448 salesforce_jigsaw_jfs_uninstall.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/salesforce_jigsaw_jfs_uninstall.pdf
echo "137/448 salesforce_vpm_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/salesforce_vpm_implementation_guide.pdf
echo "138/448 snapins.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/snapins.pdf
echo "139/448 snapins_web_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/220/latest/en-us/sfdc/pdf/snapins_web_dev_guide.pdf
echo "140/448 salesforce_client_autoupdate_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/222/latest/en-us/sfdc/pdf/salesforce_client_autoupdate_cheatsheet.pdf
echo "141/448 salesforce_offline_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/222/latest/en-us/sfdc/pdf/salesforce_offline_cheatsheet.pdf
echo "142/448 salesforce_office_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/222/latest/en-us/sfdc/pdf/salesforce_office_release_notes.pdf
echo "143/448 salesforce_offline_release_notes.pdf"
curl -sLO https://resources.docs.salesforce.com/222/latest/en-us/sfdc/pdf/salesforce_offline_release_notes.pdf
echo "144/448 salesforce_agent_console_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_agent_console_cheatsheet.pdf
echo "145/448 salesforce_analytics_folder_sharing_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_analytics_folder_sharing_cheatsheet.pdf
echo "146/448 salesforce_analytics_overview_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_analytics_overview_cheatsheet.pdf
echo "147/448 salesforce_answers_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_answers_implementation_guide.pdf
echo "148/448 salesforce_assets_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_assets_cheatsheet.pdf
echo "149/448 salesforce_busprocess_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_busprocess_cheatsheet.pdf
echo "150/448 salesforce_campaigns_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_campaigns_cheatsheet.pdf
echo "151/448 salesforce_case_feed_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_case_feed_cheatsheet.pdf
echo "152/448 salesforce_case_interaction_setup_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_case_interaction_setup_cheatsheet.pdf
echo "153/448 salesforce_conflict_res_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_conflict_res_cheatsheet.pdf
echo "154/448 salesforce_content_delivery_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_content_delivery_cheatsheet.pdf
echo "155/448 salesforce_convertleads_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_convertleads_cheatsheet.pdf
echo "156/448 salesforce_customer_portal_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_customer_portal_implementation_guide.pdf
echo "157/448 salesforce_report_cross_filters_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_report_cross_filters_cheatsheet.pdf
echo "158/448 salesforce_dashboards_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_dashboards_cheatsheet.pdf
echo "159/448 salesforce_data_quality_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_data_quality_cheatsheet.pdf
echo "160/448 salesforce_data_quality_duplicate_prevention.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_data_quality_duplicate_prevention.pdf
echo "161/448 salesforce_dashboard_filters_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_dashboard_filters_cheatsheet.pdf
echo "162/448 salesforce_divisions_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_divisions_cheatsheet.pdf
echo "163/448 salesforce_dynamic_dashboards_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_dynamic_dashboards_cheatsheet.pdf
echo "164/448 salesforce_forecastFAQ_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_forecastFAQ_cheatsheet.pdf
echo "165/448 salesforce_forecastsetup_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_forecastsetup_cheatsheet.pdf
echo "166/448 salesforce_forecastuser_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_forecastuser_cheatsheet.pdf
echo "167/448 salesforce_formulas_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_formulas_cheatsheet.pdf
echo "168/448 salesforce_groupcal_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_groupcal_cheatsheet.pdf
echo "169/448 salesforce_HTMLtemplates_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_HTMLtemplates_cheatsheet.pdf
echo "170/448 salesforce_ideas_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_ideas_cheatsheet.pdf
echo "171/448 salesforce_ideas_theme_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_ideas_theme_cheatsheet.pdf
echo "172/448 salesforce_import_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_import_cheatsheet.pdf
echo "173/448 salesforce_leads_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_leads_cheatsheet.pdf
echo "174/448 salesforce_mailmerge.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_mailmerge.pdf
echo "175/448 salesforce_office_edition_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_office_edition_cheatsheet.pdf
echo "176/448 salesforce_opportunity_trending_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_opportunity_trending_cheatsheet.pdf
echo "177/448 salesforce_orders_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_orders_cheatsheet.pdf
echo "178/448 salesforce_platform_encryption_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_platform_encryption_tipsheet.pdf
echo "179/448 salesforce_portal_to_community_migration_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_portal_to_community_migration_cheatsheet.pdf
echo "180/448 salesforce_products_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_products_cheatsheet.pdf
echo "181/448 salesforce_profile_tabs_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_profile_tabs_cheatsheet.pdf
echo "182/448 salesforce_questions_portal_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_questions_portal_implementation_guide.pdf
echo "183/448 salesforce_report_cross_filters_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_report_cross_filters_cheatsheet.pdf
echo "184/448 salesforce_report_joined_format_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_report_joined_format_cheatsheet.pdf
echo "185/448 salesforce_report_summary_functions_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_report_summary_functions_cheatsheet.pdf
echo "186/448 salesforce_reportperformance_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_reportperformance_cheatsheet.pdf
echo "187/448 salesforce_reports_bucketing_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_reports_bucketing_cheatsheet.pdf
echo "188/448 salesforce_reports_schedule_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_reports_schedule_cheatsheet.pdf
echo "189/448 salesforce_salesrep_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_salesrep_cheatsheet.pdf
echo "190/448 salesforce_selfservice_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_selfservice_cheatsheet.pdf
echo "191/448 salesforce_sharing_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_sharing_cheatsheet.pdf
echo "192/448 salesforce_solutions_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_solutions_cheatsheet.pdf
echo "193/448 salesforce_supportadmin_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_supportadmin_cheatsheet.pdf
echo "194/448 salesforce_supportrep_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_supportrep_cheatsheet.pdf
echo "195/448 salesforce_TEadmin_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_TEadmin_cheatsheet.pdf
echo "196/448 salesforce_TEuser_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_TEuser_cheatsheet.pdf
echo "197/448 salesforce_views_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/224/latest/en-us/sfdc/pdf/salesforce_views_cheatsheet.pdf

# current
echo "198/448 BuddyMediaAnalytics.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaAnalytics.pdf
echo "199/448 BuddyMediaChannelAdminGuide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaChannelAdminGuide.pdf
echo "200/448 BuddyMediaConversationBuddy.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaConversationBuddy.pdf
echo "201/448 BuddyMediaDataAdapter.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaDataAdapter.pdf
echo "202/448 BuddyMediaDataAdaptorDeveloperGuide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaDataAdaptorDeveloperGuide.pdf
echo "203/448 BuddyMediaFacebookGlobalPages.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaFacebookGlobalPages.pdf
echo "204/448 BuddyMediaGettingStarted.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaGettingStarted.pdf
echo "205/448 BuddyMediaImplementationGuide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaImplementationGuide.pdf
echo "206/448 BuddyMediaProfileBuddy.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaProfileBuddy.pdf
echo "207/448 BuddyMediaReachBuddy.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaReachBuddy.pdf
echo "208/448 BuddyMediaYouTubeBrandChannels.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaYouTubeBrandChannels.pdf
echo "209/448 BuddyMediaYouTubeOneChannelFAQ.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/BuddyMediaYouTubeOneChannelFAQ.pdf
echo "210/448 MarketingCloudBuddyMediaImplementationGuide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/buddymedia/en-us/static/pdf/MarketingCloudBuddyMediaImplementationGuide.pdf
echo "211/448 CheckoutUserGuide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/CheckoutUserGuide.pdf
echo "212/448 SF_Apex_Code_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Apex_Code_cheatsheet_web.pdf
echo "213/448 SF_CRM_Lightning_Experience_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_CRM_Lightning_Experience_web.pdf
echo "214/448 SF_CRM_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_CRM_cheatsheet_web.pdf
echo "215/448 SF_Custom_Metadata_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Custom_Metadata_cheatsheet_web.pdf
echo "216/448 SF_Formulas_Developer_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Formulas_Developer_cheatsheet_web.pdf
echo "217/448 SF_Git_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Git_cheatsheet_web.pdf
echo "218/448 SF_LightningComponents_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_LightningComponents_cheatsheet_web.pdf
echo "219/448 SF_Process_Automation_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Process_Automation_cheatsheet_web.pdf
echo "220/448 SF_Query_Search_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Query_Search_cheatsheet_web.pdf
echo "221/448 Cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Record-Locking-Cheatsheet_web.pdf
echo "222/448 SF_Reports_and_Dashboards_Rest_API_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Reports_and_Dashboards_Rest_API_web.pdf
echo "223/448 SF_Rest_API_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Rest_API_cheatsheet_web.pdf
echo "224/448 Admin_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_S1-Admin_cheatsheet_web.pdf
echo "225/448 Developer_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_S1-Developer_cheatsheet_web.pdf
echo "226/448 SF_Security_Admin_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Security_Admin_cheatsheet_web.pdf
echo "227/448 SF_Security_Developer_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Security_Developer_cheatsheet_web.pdf
echo "228/448 SF_Service_Cloud_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Service_Cloud_cheatsheet_web.pdf
echo "229/448 SF_Soap_API_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Soap_API_cheatsheet_web.pdf
echo "230/448 SF_Visualforce_Developer_cheatsheet_web.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SF_Visualforce_Developer_cheatsheet_web.pdf
echo "231/448 SK1_AbandonedCart.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK1_AbandonedCart.pdf
echo "232/448 SK2_CouponRedemption.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK2_CouponRedemption.pdf
echo "233/448 SK3_OrderonBehalfof.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK3_OrderonBehalfof.pdf
echo "234/448 SK4_PersonalizedMarketingRecommendations.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK4_PersonalizedMarketingRecommendations.pdf
echo "235/448 SK5_TransactionalEmails.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK5_TransactionalEmails.pdf
echo "236/448 SK6_CancelOrders.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK6_CancelOrders.pdf
echo "237/448 SK7_ConversationalCommerce.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK7_ConversationalCommerce.pdf
echo "238/448 SK8_SeamlessIdentity.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK8_SeamlessIdentity.pdf
echo "239/448 SK9_CrossCloudEngagementDataModels.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/SK9_CrossCloudEngagementDataModels.pdf
echo "240/448 help.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/chatter-edition-help.pdf
echo "241/448 external.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/chatter-external.pdf
echo "242/448 help.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/chatter-help.pdf
echo "243/448 overview.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/ext-svc-overview.pdf
echo "244/448 field_service_lightning_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/field_service_lightning_guide.pdf
echo "245/448 identity_connect_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/identity_connect_impl_guide.pdf
echo "246/448 salesforce_query_search_optimization_developer_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/salesforce_query_search_optimization_developer_cheatsheet.pdf
echo "247/448 InsightsPartnerOverviews.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/InsightsPartnerOverviews.pdf
echo "248/448 MCNov13ReleaseNotes.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/MCNov13ReleaseNotes.pdf
echo "249/448 MCReleaseNotesSpring14.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/MCReleaseNotesSpring14.pdf
echo "250/448 MC_ReleaseNotes_August13.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/MC_ReleaseNotes_August13.pdf
echo "251/448 StreamActivityFAQ.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/other/en-us/static/pdf/StreamActivityFAQ.pdf
echo "252/448 MarketingCloudRadian6Introduction.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/MarketingCloudRadian6Introduction.pdf
echo "253/448 Radian6AnalysisDashboard.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6AnalysisDashboard.pdf
echo "254/448 Radian6EngagementConsole.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6EngagementConsole.pdf
echo "255/448 Radian6EngagementConsoleSpecifications.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6EngagementConsoleSpecifications.pdf
echo "256/448 Radian6FacebookManagedAccounts.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6FacebookManagedAccounts.pdf
echo "257/448 Radian6Insights.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6Insights.pdf
echo "258/448 Radian6Mobile.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6Mobile.pdf
echo "259/448 Radian6Reports.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6Reports.pdf
echo "260/448 Radian6SummaryDashboard.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6SummaryDashboard.pdf
echo "261/448 Radian6SuperUsers.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6SuperUsers.pdf
echo "262/448 Radian6TopicProfile.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6TopicProfile.pdf
echo "263/448 Radian6TopicProfileOptimization.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6TopicProfileOptimization.pdf
echo "264/448 Radian6TwitterManagedAccounts.pdf"
curl -sLO https://resources.docs.salesforce.com/rel1/radian6/en-us/static/pdf/Radian6TwitterManagedAccounts.pdf
echo "265/448 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/0/4/en-us/pdf/service_sdk_android.pdf
echo "266/448 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/1/2/en-us/pdf/service_sdk_ios.pdf
echo "267/448 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/2/0/en-us/pdf/service_sdk_ios.pdf
echo "268/448 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/206/0/en-us/pdf/service_sdk_android.pdf
echo "269/448 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/208/0/en-us/pdf/service_sdk_ios.pdf
echo "270/448 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/208/0/en-us/pdf/service_sdk_android.pdf
echo "271/448 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/210/0/en-us/pdf/service_sdk_ios.pdf
echo "272/448 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/210/0/en-us/pdf/service_sdk_android.pdf
echo "273/448 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/214/0/en-us/pdf/service_sdk_android.pdf
echo "274/448 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/214/0/en-us/pdf/service_sdk_ios.pdf
echo "275/448 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/218/0/en-us/pdf/service_sdk_ios.pdf
echo "276/448 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/218/0/en-us/pdf/service_sdk_android.pdf
echo "277/448 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/220/0/en-us/pdf/service_sdk_android.pdf
echo "278/448 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/220/0/en-us/pdf/service_sdk_ios.pdf
echo "279/448 service_sdk_android.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/222/0/en-us/pdf/service_sdk_android.pdf
echo "280/448 service_sdk_ios.pdf"
curl -sLO https://resources.docs.salesforce.com/servicesdk/222/0/en-us/pdf/service_sdk_ios.pdf
echo "281/448 apex_ajax.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/apex_ajax.pdf
echo "282/448 apex_api.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/apex_api.pdf
echo "283/448 api_action.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_action.pdf
echo "284/448 api_asynch.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_asynch.pdf
echo "285/448 api_bulk_v2.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_bulk_v2.pdf
echo "286/448 api_console.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_console.pdf
echo "287/448 api_cti.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_cti.pdf
echo "288/448 api_meta.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_meta.pdf
echo "289/448 api_rest.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_rest.pdf
echo "290/448 api_rest_industries.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_rest_industries.pdf
echo "291/448 api_social.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_social.pdf
echo "292/448 api_streaming.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_streaming.pdf
echo "293/448 api_tooling.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_tooling.pdf
echo "294/448 api_ui.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/api_ui.pdf
echo "295/448 appexchange_install_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/appexchange_install_guide.pdf
echo "296/448 appexchange_publishing_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/appexchange_publishing_guide.pdf
echo "297/448 apps.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/apps.pdf
echo "298/448 async_soql_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/async_soql_guide.pdf
echo "299/448 basics.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/basics.pdf
echo "300/448 bi_admin_guide_security.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_admin_guide_security.pdf
echo "301/448 bi_admin_guide_setup.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_admin_guide_setup.pdf
echo "302/448 bi_dev_guide_bindings.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_bindings.pdf
echo "303/448 bi_dev_guide_ext_data.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_ext_data.pdf
echo "304/448 bi_dev_guide_ext_data_format.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_ext_data_format.pdf
echo "305/448 bi_dev_guide_json.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_json.pdf
echo "306/448 bi_dev_guide_rest.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_rest.pdf
echo "307/448 bi_dev_guide_saql.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_saql.pdf
echo "308/448 bi_dev_guide_sdk.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_sdk.pdf
echo "309/448 bi_dev_guide_wave_templates.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_wave_templates.pdf
echo "310/448 bi_dev_guide_xmd.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/bi_dev_guide_xmd.pdf
echo "311/448 big_objects_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/big_objects_guide.pdf
echo "312/448 canvas_framework.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/canvas_framework.pdf
echo "313/448 case_feed_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/case_feed_dev_guide.pdf
echo "314/448 chatter.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/chatter.pdf
echo "315/448 collaboration.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/collaboration.pdf
echo "316/448 collaboration_admin.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/collaboration_admin.pdf
echo "317/448 communities.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/communities.pdf
echo "318/448 communities_dev.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/communities_dev.pdf
echo "319/448 console.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/console.pdf
echo "320/448 custom_metadata_types_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/custom_metadata_types_impl_guide.pdf
echo "321/448 data_dot_com_clean_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/data_dot_com_clean_impl_guide.pdf
echo "322/448 datacom_salesforce_record_matching.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/datacom_salesforce_record_matching.pdf
echo "323/448 datadotcom_api_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/datadotcom_api_dev_guide.pdf
echo "324/448 deploy_sandboxes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/deploy_sandboxes.pdf
echo "325/448 draes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/draes.pdf
echo "326/448 eclipse.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/eclipse.pdf
echo "327/448 einstein_platform_services.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/einstein_platform_services.pdf
echo "328/448 extend_click.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/extend_click.pdf
echo "329/448 extend_code.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/extend_code.pdf
echo "330/448 federated_search.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/federated_search.pdf
echo "331/448 field_history_retention.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/field_history_retention.pdf
echo "332/448 financial_services.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/financial_services.pdf
echo "333/448 forecasts.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/forecasts.pdf
echo "334/448 formula_date_time_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/formula_date_time_tipsheet.pdf
echo "335/448 fsc_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/fsc_dev_guide.pdf
echo "336/448 generate_orders_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/generate_orders_implementation_guide.pdf
echo "337/448 health_cloud_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/health_cloud_dev_guide.pdf
echo "338/448 healthcare.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/healthcare.pdf
echo "339/448 integration_patterns_and_practices.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/integration_patterns_and_practices.pdf
echo "340/448 jsapi_chatteranswers.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/jsapi_chatteranswers.pdf
echo "341/448 lex.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/lex.pdf
echo "342/448 lightning.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/lightning.pdf
echo "343/448 lightning_adoption_javascript_button_conversion.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/lightning_adoption_javascript_button_conversion.pdf
echo "344/448 lightning_experience_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/lightning_experience_guide.pdf
echo "345/448 lightning_knowledge_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/lightning_knowledge_guide.pdf
echo "346/448 mobile_sdk.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/mobile_sdk.pdf
echo "347/448 object_reference.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/object_reference.pdf
echo "348/448 oem_user_license_comparison_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/oem_user_license_comparison_tipsheet.pdf
echo "349/448 omnichannel_supervisor.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/omnichannel_supervisor.pdf
echo "350/448 organization_sync.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/organization_sync.pdf
echo "351/448 platform_events.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/platform_events.pdf
echo "352/448 sales_einstein_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sales_einstein_implementation_guide.pdf
echo "353/448 salesforce1_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_guide.pdf
echo "354/448 salesforce1_mobile_security.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_mobile_security.pdf
echo "355/448 salesforce1_url_schemes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_url_schemes.pdf
echo "356/448 salesforce1_user_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce1_user_guide.pdf
echo "357/448 salesforce_B2C_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_B2C_implementation_guide.pdf
echo "358/448 salesforce_analytics_rest_api.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_analytics_rest_api.pdf
echo "359/448 salesforce_apex_language_reference.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_apex_language_reference.pdf
echo "360/448 salesforce_app_limits_cheatsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_app_limits_cheatsheet.pdf
echo "361/448 salesforce_campaign_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_campaign_implementation_guide.pdf
echo "362/448 salesforce_case_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_case_implementation_guide.pdf
echo "363/448 salesforce_chatter_rest_api.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_chatter_rest_api.pdf
echo "364/448 salesforce_chatterplus_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_chatterplus_tipsheet.pdf
echo "365/448 salesforce_communities_managers_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_communities_managers_guide.pdf
echo "366/448 salesforce_community_identity_templates.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_community_identity_templates.pdf
echo "367/448 salesforce_console_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_console_impl_guide.pdf
echo "368/448 salesforce_content_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_content_implementation_guide.pdf
echo "369/448 salesforce_dashboard_samples.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_dashboard_samples.pdf
echo "370/448 salesforce_data_import_wizard_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_data_import_wizard_tipsheet.pdf
echo "371/448 salesforce_data_loader.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_data_loader.pdf
echo "372/448 salesforce_defer_sharing_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_defer_sharing_tipsheet.pdf
echo "373/448 salesforce_developer_environment_dotnet_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_developer_environment_dotnet_tipsheet.pdf
echo "374/448 salesforce_developer_environment_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_developer_environment_tipsheet.pdf
echo "375/448 salesforce_ee_upgrade_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_ee_upgrade_guide.pdf
echo "376/448 salesforce_entitlements_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_entitlements_implementation_guide.pdf
echo "377/448 salesforce_exchange_sync_admin_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_exchange_sync_admin_implementation_guide.pdf
echo "378/448 salesforce_exchange_sync_user.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_exchange_sync_user.pdf
echo "379/448 salesforce_external_identity_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_external_identity_implementation_guide.pdf
echo "380/448 salesforce_field_names_reference.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_field_names_reference.pdf
echo "381/448 salesforce_file_sync_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_file_sync_impl_guide.pdf
echo "382/448 salesforce_files_connect_implementation.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_files_connect_implementation.pdf
echo "383/448 salesforce_finserv_admin_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_admin_guide.pdf
echo "384/448 salesforce_finserv_install_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_install_guide.pdf
echo "385/448 salesforce_finserv_quick_start.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_quick_start.pdf
echo "386/448 salesforce_finserv_upgrade_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_finserv_upgrade_guide.pdf
echo "387/448 salesforce_flash_builder.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_flash_builder.pdf
echo "388/448 salesforce_flash_builder_quickstart.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_flash_builder_quickstart.pdf
echo "389/448 salesforce_formula_size_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_formula_size_tipsheet.pdf
echo "390/448 salesforce_guided_engagement.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_guided_engagement.pdf
echo "391/448 salesforce_health_cloud_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_health_cloud_impl_guide.pdf
echo "392/448 salesforce_ideas_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_ideas_implementation_guide.pdf
echo "393/448 salesforce_identity_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_identity_implementation_guide.pdf
echo "394/448 salesforce_implementing_territory_mgmt2_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_implementing_territory_mgmt2_guide.pdf
echo "395/448 salesforce_knowledge_dev_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_knowledge_dev_guide.pdf
echo "396/448 salesforce_knowledge_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_knowledge_implementation_guide.pdf
echo "397/448 salesforce_large_data_volumes_bp.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_large_data_volumes_bp.pdf
echo "398/448 salesforce_lead_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_lead_implementation_guide.pdf
echo "399/448 salesforce_limits_practices.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_limits_practices.pdf
echo "400/448 salesforce_lma_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_lma_guide.pdf
echo "401/448 salesforce_mailmerge_upload_guidelines.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_mailmerge_upload_guidelines.pdf
echo "402/448 salesforce_massdelete_undoimport.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_massdelete_undoimport.pdf
echo "403/448 salesforce_migration_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_migration_guide.pdf
echo "404/448 salesforce_mobile_push_notifications_implementation.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_mobile_push_notifications_implementation.pdf
echo "405/448 salesforce_packaging_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_packaging_guide.pdf
echo "406/448 salesforce_pages_developers_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_pages_developers_guide.pdf
echo "407/448 salesforce_partner_portal_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_partner_portal_guide.pdf
echo "408/448 salesforce_placeorder_rest_api.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_placeorder_rest_api.pdf
echo "409/448 salesforce_platform_encryption_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_platform_encryption_implementation_guide.pdf
echo "410/448 salesforce_platform_glossary.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_platform_glossary.pdf
echo "411/448 salesforce_platform_portal_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_platform_portal_implementation_guide.pdf
echo "412/448 salesforce_record_access_under_the_hood.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_record_access_under_the_hood.pdf
echo "413/448 salesforce_relgroups_getstart.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_relgroups_getstart.pdf
echo "414/448 salesforce_reports_enhanced_reports_tab_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_reports_enhanced_reports_tab_tipsheet.pdf
echo "415/448 salesforce_security_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_security_impl_guide.pdf
echo "416/448 salesforce_selfservice_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_selfservice_implementation_guide.pdf
echo "417/448 salesforce_sharing_users_tipsheet.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_sharing_users_tipsheet.pdf
echo "418/448 salesforce_single_sign_on.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_single_sign_on.pdf
echo "419/448 salesforce_solutions_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_solutions_implementation_guide.pdf
echo "420/448 salesforce_soql_sosl.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_soql_sosl.pdf
echo "421/448 salesforce_technical_requirements.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_technical_requirements.pdf
echo "422/448 salesforce_useful_approval_processes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_useful_approval_processes.pdf
echo "423/448 salesforce_useful_formula_fields.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_useful_formula_fields.pdf
echo "424/448 salesforce_useful_validation_formulas.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_useful_validation_formulas.pdf
echo "425/448 salesforce_useful_workflow_rules.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_useful_workflow_rules.pdf
echo "426/448 salesforce_using_multiple_currencies.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_using_multiple_currencies.pdf
echo "427/448 salesforce_visualforce_best_practices.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_visualforce_best_practices.pdf
echo "428/448 salesforce_voice_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_voice_implementation_guide.pdf
echo "429/448 salesforce_wm_peripherals_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/salesforce_wm_peripherals_implementation_guide.pdf
echo "430/448 secure_coding.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/secure_coding.pdf
echo "431/448 security_certificate_changes.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/security_certificate_changes.pdf
echo "432/448 service_presence_administrators.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/service_presence_administrators.pdf
echo "433/448 service_presence_developer_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/service_presence_developer_guide.pdf
echo "434/448 setup.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/setup.pdf
echo "435/448 sfdx_cli_reference.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sfdx_cli_reference.pdf
echo "436/448 sfdx_dev.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sfdx_dev.pdf
echo "437/448 sfdx_setup.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sfdx_setup.pdf
echo "438/448 sfo_getting_started_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sfo_getting_started_guide.pdf
echo "439/448 sharing_architecture.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sharing_architecture.pdf
echo "440/448 smb_sales_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/smb_sales_impl_guide.pdf
echo "441/448 smb_sales_impl_guide_2.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/smb_sales_impl_guide_2.pdf
echo "442/448 social_customer_service_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/social_customer_service_impl_guide.pdf
echo "443/448 sos_administrators.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/sos_administrators.pdf
echo "444/448 state_country_picklists_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/state_country_picklists_impl_guide.pdf
echo "445/448 support.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/support.pdf
echo "446/448 team_selling_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/team_selling_implementation_guide.pdf
echo "447/448 utility_bar_impl_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/utility_bar_impl_guide.pdf
echo "448/448 workcom_implementation_guide.pdf"
curl -sLO https://resources.docs.salesforce.com/sfdc/pdf/workcom_implementation_guide.pdf
echo "Done"
